name: CI

on:
  push:
    
  pull_request:
    branches:  
    - master
    - develop 

jobs:
  CI:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Installing Cocoapods
      run: |
       pod install
       pod update

    - name: Releasing Secrets
      run: |
       gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.key }}" --output SpaceDash/Model/Secrets.swift SpaceDash/Model/Secrets.swift.gpg

    - name: Installing FastLane
      run: | 
        bundle install
        bundle update fastlane
         
 
    - name: Running Tests
      run: bundle exec fastlane tests    
